### PR TITLE
Ported MessageSizeEstimator per #48

### PR DESCRIPTION
**Pull request by mgobec**
Initial port of MessageSizeEstimator and its implementation DefaultMessageSizeEstimator

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@mgobec looks like there's an issue with the NUnit binaries on Windows. Mono build ran fine but the Windows one needs some love. Could you double check to make sure that the project references the NUnit binaries in the correct location?

**Comment by mgobec** [comment]
@Aaronontheweb I updated test project file with nuget because it was missing the referenced libraries. It changed to packages folder which is 2 levels instead of 3 levels up. This is where binaries to faker and nunit are pulled by nuget. Mono build now passed because the path is now correct while windows one failed with missing libraries. Does the build automatically retrieves nuget packages ?

**Comment by Aaronontheweb** [comment]
@mgobec yessir, it does do NuGet package restore. Your previous PR worked fine but I think Visual Studio / NuGet might have goofed on re-writing the binary paths. Go ahead and push up your latest commits and TeamCity will pick up them up and re-run the build.

**Comment by mgobec** [comment]
@Aaronontheweb I reverted binary paths and the build is ok now.

**Comment by Aaronontheweb** [comment]
Thanks @mgobec! Merged.

**Pull request merged**
