### PR TITLE
replaced RAKE with FAKE build system

### LINKED ISSUE #13: Rewrite build script to use F# / FAKE
To make life easier for the build server, so we don't need to include the Rails installer junk in the path.

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #13
added HELP build instructions

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Build server has been reconfigured to use FAKE instead of RAKE, so this pull request should be able to start successfully.

**Comment by Aaronontheweb** [comment]
DOH! Stupid .NET 3.5 support :(

**Comment by nayato** [comment]
does it make sense to keep 3.5 support at this age?

**Comment by Aaronontheweb** [comment]
@nayato probably not - I wanted folks building production-ready Windows Desktop apps to be able to use it, and sadly .NET 3.5 is the "safe" option for most of those systems.

The Windows 10 upgrade should help change that, hopefully.

**Comment by Aaronontheweb** [comment]
That being said - upgraded the build server and everything passes now :)

**Pull request merged**
